# Generated by Django 3.1.6 on 2021-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_undangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
