# Generated by Django 3.1.6 on 2021-02-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_undangan', '0004_pengantin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucapan', models.TextField()),
                ('sumbangan', models.CharField(blank=True, max_length=200, null=True)),
                ('tampilkan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_undangan.tamuundangan')),
            ],
        ),
    ]
