# Generated by Django 3.1.6 on 2021-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_undangan', '0005_pesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamuundangan',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
